// Generated by filthy-panty. Do not edit by hand.
import type { ResourceApi } from "filthy-panty";
import { ids } from "./ids";

/** Typed references for resources defined in filthypanty/. */
export const api = {
  agents: {
    myAgent: { kind: "agent", name: "my-agent", id: ids.agents["my-agent"], project: "sandbox-stateless", environment: "development", endpointId: "env-e988jf3e", projectSlug: "sandbox-stateless", environmentSlug: "development" },
  },
  workspaces: ids.workspaces,
  sandboxes: ids.sandboxes,
  cronJobs: ids.cronJobs,
  skills: ids.skills,
  tools: ids.tools,
} as const satisfies ResourceApi;
