// Generated by filthy-panty. Do not edit by hand.
import type { ResourceApi } from "filthy-panty";
import { ids } from "./ids";

/** Typed references for resources defined in filthypanty/. */
export const api = {
  agents: {
    "compute": { kind: "agent", name: "compute", id: ids.agents["compute"], project: "sandbox-stateless", environment: "development" },
  },
  workspaces: ids.workspaces,
  sandboxes: ids.sandboxes,
  cronJobs: ids.cronJobs,
  skills: ids.skills,
  tools: ids.tools,
} as const satisfies ResourceApi;
