// Generated by filthy-panty. Do not edit by hand.
export const ids = {
  "agents": {
    "compute": "agent_compute_placeholder"
  },
  "workspaces": {},
  "sandboxes": {
    "stateless-sandbox": "sandbox_stateless_placeholder"
  },
  "cronJobs": {},
  "skills": {},
  "tools": {}
} as const;
export const agents = ids.agents;
export const workspaces = ids.workspaces;
export const sandboxes = ids.sandboxes;
export const cronJobs = ids.cronJobs;
export const skills = ids.skills;
export const tools = ids.tools;
