// Generated by filthy-panty. Do not edit by hand.
export const ids = {
  "agents": {
    "my-agent": "p1764r22pdrrjw0nmcm2v77a7h88nj0x"
  },
  "workspaces": {},
  "sandboxes": {
    "stateless-sandbox": "q17fp0dqsqzy3n2bqtayp0xves88nmey"
  },
  "cronJobs": {},
  "skills": {},
  "tools": {}
} as const;
export const agents = ids.agents;
export const workspaces = ids.workspaces;
export const sandboxes = ids.sandboxes;
export const cronJobs = ids.cronJobs;
export const skills = ids.skills;
export const tools = ids.tools;
