// Generated by filthy-panty. Do not edit by hand.
export const manifest = {
  "version": 1,
  "project": "sandbox-stateless",
  "environment": "development",
  "resources": [
    {
      "kind": "agent",
      "name": "my-agent",
      "config": {
        "provider": {
          "minimax": {
            "apiKey": {
              "__beeblastEnv": true,
              "name": "MINIMAX_API_KEY"
            }
          }
        },
        "model": {
          "provider": "minimax",
          "modelId": "MiniMax-M3"
        },
        "agent": {
          "system": "You only have the bash tool — there is no persistent workspace.\nEach bash call is a fresh container, so write any files and run them in the SAME command.\nReport stdout and status for every run."
        },
        "sandbox": "stateless-sandbox"
      }
    },
    {
      "kind": "sandbox",
      "name": "stateless-sandbox",
      "config": {
        "provider": "lambda",
        "network": {
          "mode": "deny-all"
        },
        "permissionMode": "bypass",
        "timeout": 60
      }
    }
  ]
} as const;
