/**
 * Writes deterministic generated IDs and a typed agent client for app code.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { CliManifest, GeneratedIds } from "./contracts.ts";
import { PROJECT_DIR } from "./config.ts";

export async function writeGeneratedFiles(
  manifest: CliManifest,
  ids: GeneratedIds,
  cwd = process.cwd(),
): Promise<void> {
  const dir = resolve(cwd, PROJECT_DIR, "generated");
  await mkdir(dir, { recursive: true });
  await writeFile(resolve(dir, "ids.ts"), idsFile(ids), "utf8");
  await writeFile(resolve(dir, "resources.ts"), resourcesFile(manifest), "utf8");
  await writeFile(resolve(dir, "types.ts"), typesFile(), "utf8");
  await writeFile(resolve(dir, "client.ts"), clientFile(manifest, ids), "utf8");
}

function idsFile(ids: GeneratedIds): string {
  return `// Generated by filthy-panty. Do not edit by hand.\n` +
    `export const ids = ${JSON.stringify(ids, null, 2)} as const;\n` +
    `export const agents = ids.agents;\n` +
    `export const workspaces = ids.workspaces;\n` +
    `export const sandboxes = ids.sandboxes;\n` +
    `export const cronJobs = ids.cronJobs;\n`;
}

function resourcesFile(manifest: CliManifest): string {
  return `// Generated by filthy-panty. Do not edit by hand.\n` +
    `export const manifest = ${JSON.stringify(manifest, null, 2)} as const;\n`;
}

function typesFile(): string {
  return `// Generated by filthy-panty. Do not edit by hand.\n` +
    `export type { AgentRunInput, AgentRunResult, FilthyPantyGeneratedClient } from "filthy-panty";\n`;
}

function clientFile(manifest: CliManifest, ids: GeneratedIds): string {
  const agents = Object.keys(ids.agents);
  const agentEntries = agents.map((name) =>
    `    ${JSON.stringify(name)}: client.agent(${JSON.stringify(name)}, ids.agents[${JSON.stringify(name)}]),`,
  ).join("\n");

  return `// Generated by filthy-panty. Do not edit by hand.\n` +
    `import { FilthyPantyClient } from "filthy-panty";\n` +
    `import { ids } from "./ids";\n\n` +
    `const client = new FilthyPantyClient({\n` +
    `  dashboardUrl: process.env.FILTHY_PANTY_DASHBOARD_URL,\n` +
    `  token: process.env.FILTHY_PANTY_TOKEN,\n` +
    `  project: ${JSON.stringify(manifest.project)},\n` +
    `  environment: ${JSON.stringify(manifest.environment)},\n` +
    `});\n\n` +
    `export const filthyPanty = {\n` +
    `  agents: {\n${agentEntries}\n  },\n` +
    `} as const;\n`;
}
