#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any, without the
# double quotes write_env puts around it.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  line="${line#*=}"
  if [[ ${#line} -ge 2 && ${line:0:1} == '"' && ${line: -1} == '"' ]]; then
    line="${line:1:${#line}-2}"
  fi
  printf '%s' "$line"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden. Re-prompts on a
# value with `"` or `\`: write_env quotes the value, and Node expands both
# inside the quotes when it loads ENV_FILE.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  while :; do
    if [[ -n "$current" ]]; then
      printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
      printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    IFS= read -rs input || true
    printf '\n'
    [[ -z "$input" && -n "$current" ]] && input="$current"
    [[ "$input" == *[\"\\]* ]] || break
    warn 'a value with " or \ cannot be stored in the env file; pick one without'
  done
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY="VALUE" into ENV_FILE (creates it; replaces
# any existing line). Idempotent. Quoted because Node's loadEnvFile cuts an
# unquoted value at `#` and trims its spaces, which breaks a password with
# either.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s="%s"\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — the dashboard e2e probe account, the local env, and the GitHub
# environments .github/workflows/e2e-dashboard.yaml reads. Re-runnable.
# ──────────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/apps/dashboard/.env.local"
DEV_DASHBOARD="https://dashboard.dev.broods.app"
WORKFLOW="e2e-dashboard.yaml"

# set_env_secret ENVIRONMENT NAME VALUE — a GitHub *environment* secret, which
# the workflow reads; the library's set_secret writes repo secrets.
set_env_secret() {
  local environment="$1" name="$2" value="$3"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" --env "$environment" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$environment/$name")
      printf '  %s✓ set%s %s secret %s\n' "$GREEN" "$RESET" "$environment" "$name"
      return
    fi
  fi
  SKIPPED+=("$environment secret $name (gh secret set $name --env $environment)")
  warn "skipped $environment secret $name — gh not ready; set it later"
}

TOTAL_STAGES=6

banner "Dashboard e2e probe account"

stage "WorkOS staging app — password auth and the local redirect"
say "The suites sign in through hosted AuthKit with an email + password user."
say "The pull request job runs the dashboard on the runner at localhost:3000,"
say "so that callback must be an allowed redirect."
open_url "https://dashboard.workos.com/"
step "Top left: make sure the environment is Staging (the dev stage's client)."
step "Authentication: Email + Password must be enabled."
step "Redirects: the list must contain http://localhost:3000/auth/callback"
step "  (it is there already if you sign in locally) and the dev dashboard's callback."
note "If a page looks different from this, follow the dashboard; these names are from the WorkOS docs."
pause "Both confirmed? Press Enter."

stage "WorkOS staging — create the probe user"
say "A dedicated user, not a personal one: its password lives in GitHub."
open_url "https://dashboard.workos.com/"
step "User Management → Users → Create user."
step "Email: something like e2e-probe@beeblast.co (a mailbox you can open once)."
step "Set a password. If the form offers 'email verified', tick it; otherwise"
step "  open the verification email WorkOS sends before the next stage."
step "Do not add the user to an organization: the first sign-in creates its own org,"
step "  backend account and default project on the dev stage."
ask E2E_EMAIL "Probe email:"
ask_secret E2E_PASSWORD "Probe password:"
write_env E2E_EMAIL "$E2E_EMAIL"
write_env E2E_PASSWORD "$E2E_PASSWORD"

stage "First sign-in — run the suite against the dev deployment"
say "This signs in as the probe, provisions its org and project, and runs the"
say "app suite. It proves the account before anything goes to GitHub."
if confirm "Run bun run test:app against $DEV_DASHBOARD now?"; then
  if (cd "$REPO_ROOT/apps/dashboard" && E2E_BASE_URL="$DEV_DASHBOARD" bun run test:app); then
    say "${GREEN}Suite passed.${RESET}"
  else
    warn "Suite failed. Check the login (password auth, verified email) before continuing."
  fi
else
  note "Skipped. Run it later: cd apps/dashboard && E2E_BASE_URL=$DEV_DASHBOARD bun run test:app"
fi
pause

stage "GitHub 'development' environment — secrets the workflow reads"
say "The pull request job needs the probe login and the same WorkOS values the"
say "dashboard runs with locally (read from $ENV_FILE)."
WORKOS_API_KEY="$(_existing WORKOS_API_KEY || true)"
WORKOS_CLIENT_ID="$(_existing WORKOS_CLIENT_ID || true)"
WORKOS_COOKIE_PASSWORD="$(_existing WORKOS_COOKIE_PASSWORD || true)"
if [[ -z "$WORKOS_API_KEY" || -z "$WORKOS_CLIENT_ID" || -z "$WORKOS_COOKIE_PASSWORD" ]]; then
  warn "WORKOS_API_KEY, WORKOS_CLIENT_ID or WORKOS_COOKIE_PASSWORD is missing from $ENV_FILE."
  ask_secret WORKOS_API_KEY "WorkOS staging API key (sk_test_...):"
  ask WORKOS_CLIENT_ID "WorkOS staging client id (client_...):"
  ask_secret WORKOS_COOKIE_PASSWORD "WorkOS cookie password (32+ chars):"
fi
step "Secrets to set: DASHBOARD_E2E_EMAIL, DASHBOARD_E2E_PASSWORD, WORKOS_API_KEY,"
step "  WORKOS_CLIENT_ID, WORKOS_COOKIE_PASSWORD. The var NEXT_PUBLIC_CONVEX_URL already exists."
if confirm "Write these five secrets to the 'development' environment?"; then
  set_env_secret development DASHBOARD_E2E_EMAIL "$E2E_EMAIL"
  set_env_secret development DASHBOARD_E2E_PASSWORD "$E2E_PASSWORD"
  set_env_secret development WORKOS_API_KEY "$WORKOS_API_KEY"
  set_env_secret development WORKOS_CLIENT_ID "$WORKOS_CLIENT_ID"
  set_env_secret development WORKOS_COOKIE_PASSWORD "$WORKOS_COOKIE_PASSWORD"
else
  SKIPPED+=("development environment secrets")
fi
pause

stage "GitHub 'production' environment — optional"
say "After a main rollout the suites run against dashboard.broods.app, which"
say "signs in through the WorkOS Production environment: a separate user."
if confirm "Create a production probe now?"; then
  open_url "https://dashboard.workos.com/"
  step "Switch the environment to Production, then User Management → Users → Create user,"
  step "  the same way as staging."
  ask PROD_E2E_EMAIL "Production probe email:"
  ask_secret PROD_E2E_PASSWORD "Production probe password:"
  set_env_secret production DASHBOARD_E2E_EMAIL "$PROD_E2E_EMAIL"
  set_env_secret production DASHBOARD_E2E_PASSWORD "$PROD_E2E_PASSWORD"
else
  note "Skipped. The 'deployed' job on main fails on its first step until these exist."
fi
pause

stage "Run the workflow once against dev"
say "Dispatches the 'deployed' job from the branch that carries the workflow."
say "The workflow file must already be pushed on that branch."
ask WORKFLOW_REF "Branch to dispatch from:"
if confirm "gh workflow run $WORKFLOW --ref $WORKFLOW_REF -f base_url=$DEV_DASHBOARD ?"; then
  if gh workflow run "$WORKFLOW" --ref "$WORKFLOW_REF" -f "base_url=$DEV_DASHBOARD"; then
    say "Dispatched. Watch it with: gh run list --workflow=$WORKFLOW"
  else
    warn "Dispatch failed; the workflow file must be on '$WORKFLOW_REF' on the remote."
  fi
else
  note "Skipped. Later: gh workflow run $WORKFLOW --ref <branch> -f base_url=$DEV_DASHBOARD"
fi
pause

finish
