/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AccountConfig": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AccountManage": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "AccountSignupRateLimit": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AccountTool": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AgentConfig": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AsyncAgentResult": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AsyncToolResult": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Conversations": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Cron": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Filesystem": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "HarnessProcessing": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MicrovmArtifacts": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "PersistentSandboxInstance": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ProcessedEvents": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SandboxConfig": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Skills": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ToolBundles": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Usage": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WorkspaceConfig": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}
