/**
 * Prints Traefik config generated from the route table.
 *
 *   bun src/generate.ts kubernetes [stage...]   cluster resources for ../infra
 *   bun src/generate.ts file <core> <config> <gateway>   file provider, self-hosting
 */
import {
  renderFileConfig,
  renderKubernetes,
  type KubeStage,
} from "./traefik.ts";

const NAMESPACE = "beeblast";

// Service names and ports from ../infra kubernetes/charts/releases.
const STAGES: readonly KubeStage[] = [
  {
    name: "production",
    host: "gateway.broods.app",
    tlsSecret: "gateway-tls",
    upstreams: {
      config: { name: "convex-prod-backend", namespace: "convex", port: 3211 },
      core: { name: "core", port: 80 },
      gateway: { name: "gateway", port: 80 },
    },
  },
  {
    name: "development",
    host: "gateway.dev.broods.app",
    tlsSecret: "gateway-dev-tls",
    upstreams: {
      config: { name: "convex-dev-backend", namespace: "convex", port: 3211 },
      core: { name: "core-dev", port: 80 },
      gateway: { name: "gateway-dev", port: 80 },
    },
  },
];

const HEADER =
  "# Generated by `bun run --filter @broods/edge generate kubernetes` in\n" +
  "# beeblastco/broods (apps/edge). Edit the route table there, not this file.\n";

const [mode, ...rest] = process.argv.slice(2);
if (mode === "kubernetes") {
  const stages = rest.length
    ? STAGES.filter((stage) => rest.includes(stage.name))
    : STAGES;
  if (stages.length !== (rest.length || STAGES.length)) {
    throw new Error(
      `Unknown stage in ${rest.join(", ")}; expected ${STAGES.map((s) => s.name).join(", ")}`,
    );
  }
  const documents = renderKubernetes(stages, NAMESPACE).map((resource) =>
    Bun.YAML.stringify(resource, null, 2),
  );
  process.stdout.write(`${HEADER}---\n${documents.join("\n---\n")}\n`);
} else if (mode === "file" && rest.length === 3) {
  const [core, config, gateway] = rest as [string, string, string];
  const file = renderFileConfig(
    { config: config, core: core, gateway: gateway },
    "web",
  );
  process.stdout.write(`${Bun.YAML.stringify(file, null, 2)}\n`);
} else {
  throw new Error(
    "Usage: generate.ts kubernetes [stage...] | file <core-url> <config-url> <gateway-url>",
  );
}
