/**
 * Prints Traefik config generated from the route table.
 *
 *   bun src/generate.ts kubernetes [--limits] [stage...]
 *     cluster resources for ../infra; --limits once PROXY protocol keeps the
 *     client address at the load balancer
 *   bun src/generate.ts file <core> <config> <gateway> [origin...]
 *     file provider for self-hosting; origins are hostnames, `*.` for
 *     subdomains, replacing the broods.app defaults
 */
import {
  renderFileConfig,
  renderKubernetes,
  type KubeStage,
} from "./traefik.ts";

const NAMESPACE = "beeblast";

// Service names and ports from ../infra kubernetes/charts/releases.
const STAGES: readonly KubeStage[] = [
  {
    name: "production",
    host: "gateway.broods.app",
    tlsSecret: "gateway-tls",
    upstreams: {
      config: { name: "convex-prod-backend", namespace: "convex", port: 3211 },
      core: { name: "core", port: 80 },
      gateway: { name: "gateway", port: 80 },
    },
  },
  {
    name: "development",
    host: "gateway.dev.broods.app",
    tlsSecret: "gateway-dev-tls",
    upstreams: {
      config: { name: "convex-dev-backend", namespace: "convex", port: 3211 },
      core: { name: "core-dev", port: 80 },
      gateway: { name: "gateway-dev", port: 80 },
    },
  },
];

const HEADER =
  "# Generated by `bun run --filter @broods/edge generate kubernetes` in\n" +
  "# beeblastco/broods (apps/edge). Edit the route table there, not this file.\n";

const [mode, ...rest] = process.argv.slice(2);
if (mode === "kubernetes") {
  const limits = rest.includes("--limits");
  // A subset rolls a stage out first, as development was.
  const names = rest.filter((arg) => arg !== "--limits");
  const unknown = names.filter((name) => !STAGES.some((s) => s.name === name));
  if (unknown.length) throw new Error(`Unknown stage: ${unknown.join(", ")}`);
  const stages = names.length
    ? STAGES.filter((stage) => names.includes(stage.name))
    : STAGES;
  const documents = renderKubernetes(stages, NAMESPACE, limits).map(
    (resource) => Bun.YAML.stringify(resource, null, 2),
  );
  process.stdout.write(`${HEADER}---\n${documents.join("\n---\n")}\n`);
} else if (mode === "file" && rest[0] && rest[1] && rest[2]) {
  const [core, config, gateway] = [rest[0], rest[1], rest[2]];
  const origins = rest.slice(3);
  const file = renderFileConfig(
    { config: config, core: core, gateway: gateway },
    origins.length ? origins : undefined,
  );
  process.stdout.write(`${Bun.YAML.stringify(file, null, 2)}\n`);
} else {
  throw new Error(
    "Usage: generate.ts kubernetes [--limits] [stage...] | file <core-url> <config-url> <gateway-url> [origin...]",
  );
}
