/**
 * CI helper to sync the embedded compaction prompt module with COMPACTION.md.
 * The harness compaction mechanism (src/harness/compaction.ts) embeds this at
 * build time; there is no default system prompt — agents define their own.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";

const COMPACTION_PROMPT_SOURCE = new URL("../COMPACTION.md", import.meta.url);
const GENERATED_DIR = new URL("../src/shared/.generated/", import.meta.url);
const COMPACTION_PROMPT_MODULE = new URL("./compaction-prompt.ts", GENERATED_DIR);

export async function syncCompactionPromptModule(): Promise<void> {
  const compactionPrompt = await readFile(COMPACTION_PROMPT_SOURCE, "utf8");
  const moduleSource = `/**
 * Embedded compaction prompt generated from COMPACTION.md at build/dev/check time.
 * Do not edit this file directly.
 */

export const DEFAULT_COMPACTION_PROMPT = ${JSON.stringify(compactionPrompt)};
`;

  await mkdir(GENERATED_DIR, { recursive: true });
  await writeFile(COMPACTION_PROMPT_MODULE, moduleSource);
}

if (import.meta.main) {
  await syncCompactionPromptModule();
}
